### ISSUE TITLE
n install won't work

### ISSUE THREAD

**Issue by zhaochunqi** [patrickleet/macbook-dev-setup#1]
I saw you installed n, and use the latest version of node.

`n use lastest` will not autodownload the node, use `n lastest` instead. 

and before install the latest, you need to create `/usr/local/n` folder first.

(Since I'm create my own version of this, I'll leave this as an issue instead a PR)

**Comment by patrickleet** [comment]
hm - used to work at least! wouldn't mind a PR if you clean that or anything else up.
